### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by DrAugus** [DrAugus/Augus#15]
- [x] leaflet in trip page 6f0fdeb0ed5daa821369595951db3298f52cdf2f  7d401187fcce9280e687e8696925b6da68b42467
- [x] support katex 3dbc37c8ef7039000225bdf1e1e985297d23b9a3
- [x] add tag, category use theme-hope 2e4478b2bd59857655280997284f6929e1087331

**Comment by DrAugus** [comment]
katex supported 3dbc37c8ef7039000225bdf1e1e985297d23b9a3
